// lib/api-mock.ts


// ══════════════════════════════════════════════
// MOCKS
// ══════════════════════════════════════════════

import {Category, News, Person} from "@/types";

export const CATEGORIES_MOCK: Category[] = [
  {
    name: "Política",
    slug: "politica",
    description: "Cobertura política nacional e estadual",
    isHighlight: false,
    color: "#C0392B"
  },
  {
    name: "Economia",
    slug: "economia",
    description: "Mercado, finanças e negócios",
    isHighlight: false,
    color: "#C0392B"
  },
  {
    name: "Esporte",
    slug: "esporte",
    description: "Futebol, olimpíadas e muito mais",
    isHighlight: false,
    color: "#C0392B"
  },
  {
    name: "Entretenimento",
    slug: "entretenimento",
    description: "Cultura, cinema, música e celebridades",
    isHighlight: false,
    color: "#C0392B"
  },
  {
    name: "Segurança",
    slug: "seguranca",
    description: "Segurança pública, ocorrências e polícia",
    isHighlight: false,
    color: "#C0392B"
  },
];

const CATEGORY_MAP = Object.fromEntries(
  CATEGORIES_MOCK.map(c => [c.slug, c])
)

export const NOTICIAS_MOCK: News[] = [

  // ── POLÍTICA (20 notícias) ─────────────────────────────────────────
  {
    id: "1",
    title: "Governo anuncia novo programa de habitação popular em Goiás",
    slug: "governo-anuncia-programa-habitacao-popular-goias",
    summary: "Iniciativa prevê construção de 500 mil unidades habitacionais até 2026 em regiões metropolitanas do estado.",
    content: `<p>O governo estadual anunciou nesta segunda-feira um ambicioso programa de habitação popular que prevê a construção de 500 mil unidades habitacionais até o final de 2026.</p><p>O programa, batizado de <strong>Casa Goiás</strong>, terá investimento total de R$ 45 bilhões e vai priorizar famílias com renda mensal de até três salários mínimos nas regiões metropolitanas de Goiânia e Aparecida de Goiânia.</p><blockquote>Este é o maior investimento em habitação da história do estado, declarou o governador durante a coletiva de imprensa.</blockquote><p>As inscrições começam no próximo mês pelo aplicativo oficial do governo. A expectativa é beneficiar mais de 1,5 milhão de pessoas até o fim do programa.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['politica'],
    author: "Ana Souza",
    publishedAt: "2025-03-10T09:00:00",
    updatedAt:  "2025-03-10T09:00:00",
    isPublished: true,
    isHighlight: true,
    isEditorial: true, 
    tags: []
  },
  {
    id: "2",
    title: "Assembleia Legislativa aprova orçamento de R$ 28 bilhões para 2026",
    slug: "assembleia-aprova-orcamento-2026",
    summary: "Votação foi aprovada por 32 votos a 9. Saúde e educação recebem maior fatia dos recursos.",
    content: `<p>A Assembleia Legislativa de Goiás aprovou nesta terça-feira o Projeto de Lei Orçamentária Anual para 2026, no valor de R$ 28,4 bilhões.</p><p>O orçamento destina 35% dos recursos para a área de saúde e 28% para educação.</p><blockquote>Aprovamos um orçamento responsável, que garante investimentos sem comprometer o equilíbrio das contas públicas.</blockquote>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1529107386315-e1a2ed48a620?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['politica'],
    author: "Carlos Lima",
    publishedAt: "2025-03-09T11:30:00",
    updatedAt:  "2025-03-09T11:30:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },
  {
    id: "3",
    title: "Prefeitura de Goiânia lança plano de mobilidade urbana para 2030",
    slug: "prefeitura-goiania-plano-mobilidade-2030",
    summary: "Projeto prevê expansão do metrô, novos corredores de BRT e 200 km de ciclovias até o final da década.",
    content: `<p>A Prefeitura de Goiânia apresentou o Plano de Mobilidade Urbana 2025-2030, com expansão do metrô até o Setor Bueno, três novos corredores de BRT e 200 km de ciclovias integradas.</p><p>O investimento total previsto é de R$ 4,2 bilhões, sendo R$ 1,8 bilhão proveniente do PAC federal.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['politica'],
    author: "Maria Santos",
    publishedAt: "2025-03-08T08:00:00",
    updatedAt:  "2025-03-08T08:00:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },
  {
    id: "4",
    title: "Senado aprova reforma tributária com impacto direto em Goiás",
    slug: "senado-aprova-reforma-tributaria-impacto-goias",
    summary: "Estado poderá perder até R$ 3 bilhões em arrecadação nos próximos cinco anos, segundo estimativas da Sefaz.",
    content: `<p>O Senado Federal concluiu a votação da reforma tributária com aprovação por 68 votos a 12. Para Goiás, as mudanças devem ter impacto significativo na arrecadação estadual, com queda estimada de R$ 3 bilhões em cinco anos.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1575505586569-646b2ca898fc?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['politica'],
    author: "Ana Souza",
    publishedAt: "2025-03-07T14:00:00",
    updatedAt:  "2025-03-07T14:00:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },
  {
    id: "5",
    title: "STF decide sobre direito à desconexão digital no trabalho remoto",
    slug: "stf-decide-direito-desconexao-digital",
    summary: "Decisão histórica pode beneficiar mais de 20 milhões de trabalhadores em regime de home office no país.",
    content: `<p>O Supremo Tribunal Federal concluiu o julgamento que estabelece o direito à desconexão digital como direito fundamental dos trabalhadores remotos, aprovado por 8 votos a 3.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['politica'],
    author: "Maria Santos",
    publishedAt: "2025-03-08T11:15:00",
    updatedAt:  "2025-03-08T11:15:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },
  {
    id: "6",
    title: "Governador sanciona lei de incentivo à inovação tecnológica em Goiás",
    slug: "governador-sanciona-lei-inovacao-tecnologica",
    summary: "Legislação prevê isenções fiscais para startups e empresas de tecnologia que se instalarem no estado.",
    content: `<p>O governador sancionou a Lei de Inovação Tecnológica de Goiás, que oferece isenções de ICMS e IPVA por cinco anos para empresas do setor que se instalarem no estado e gerarem pelo menos 10 empregos diretos.</p><p>A expectativa é atrair R$ 2 bilhões em investimentos privados até 2027 e criar 15 mil novos postos de trabalho qualificados.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['politica'],
    author: "Carlos Lima",
    publishedAt: "2025-03-06T10:00:00",
    updatedAt:  "2025-03-06T10:00:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },
  {
    id: "7",
    title: "Câmara Municipal de Goiânia aprova plano diretor revisado",
    slug: "camara-goiania-aprova-plano-diretor",
    summary: "Nova legislação urbanística define zonas de expansão e restringe construções em áreas de preservação ambiental.",
    content: `<p>A Câmara Municipal de Goiânia aprovou por 29 votos a 7 o novo Plano Diretor da cidade, que define as diretrizes de uso e ocupação do solo para os próximos 10 anos.</p><p>Entre as principais mudanças está a criação de quatro novas zonas de desenvolvimento controlado e a ampliação das áreas de proteção ambiental em 18%.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1444723121867-7a241cacace9?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['politica'],
    author: "Pedro Alves",
    publishedAt: "2025-03-05T09:00:00",
    updatedAt:  "2025-03-05T09:00:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },
  {
    id: "8",
    title: "Governo federal anuncia investimento de R$ 1,2 bilhão em estradas goianas",
    slug: "governo-federal-investimento-estradas-goianas",
    summary: "Recursos serão destinados à duplicação de rodovias federais e melhoria de acessos às regiões produtoras.",
    content: `<p>O Ministério da Infraestrutura anunciou um pacote de R$ 1,2 bilhão para obras em rodovias federais que cortam Goiás, com foco na duplicação da BR-153 entre Goiânia e Anápolis e na recuperação de 340 km da BR-060.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['politica'],
    author: "Ana Souza",
    publishedAt: "2025-03-04T14:00:00",
    updatedAt:  "2025-03-04T14:00:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },
  {
    id: "9",
    title: "Eleições municipais: pesquisa aponta favoritos nas principais cidades goianas",
    slug: "eleicoes-municipais-pesquisa-cidades-goianas",
    summary: "Levantamento indica candidatos à frente nas disputas de Goiânia, Anápolis, Aparecida e Rio Verde.",
    content: `<p>Uma pesquisa eleitoral divulgada nesta semana mapeou o cenário político nas quatro maiores cidades de Goiás a um ano das eleições municipais.</p><p>Em Goiânia, o atual prefeito lidera com 38% das intenções de voto. Em Anápolis, a disputa está mais acirrada, com três candidatos dentro da margem de erro.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1494172961521-33799ddd43a5?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['politica'],
    author: "Maria Santos",
    publishedAt: "2025-03-03T10:00:00",
    updatedAt:  "2025-03-03T10:00:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },
  {
    id: "10",
    title: "Secretaria de Educação anuncia concurso para 4.800 vagas de professores",
    slug: "secretaria-educacao-concurso-professores",
    summary: "Edital será publicado em abril com vagas para todas as disciplinas do ensino fundamental e médio.",
    content: `<p>A Secretaria de Estado da Educação de Goiás anunciou a abertura de concurso público para provimento de 4.800 vagas de professores efetivos na rede estadual de ensino.</p><p>O edital será publicado em abril e as provas devem ocorrer em julho. As vagas são distribuídas por todas as 40 coordenações regionais de ensino do estado.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['politica'],
    author: "Carlos Lima",
    publishedAt: "2025-03-02T09:00:00",
    updatedAt:  "2025-03-02T09:00:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },
  {
    id: "11",
    title: "Governo lança programa de regularização fundiária no interior goiano",
    slug: "governo-programa-regularizacao-fundiaria",
    summary: "Iniciativa beneficiará 120 mil famílias que ocupam áreas sem documentação em 80 municípios.",
    content: `<p>O programa Título Legal Goiás vai regularizar a situação de 120 mil famílias que vivem em áreas sem documentação em 80 municípios do interior do estado.</p><p>A emissão de títulos de propriedade dará acesso a financiamentos habitacionais e aumentará a segurança jurídica dos moradores.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['politica'],
    author: "Pedro Alves",
    publishedAt: "2025-03-01T08:00:00",
    updatedAt:  "2025-03-01T08:00:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },
  {
    id: "12",
    title: "UFG abre 1.200 vagas em novos cursos de graduação",
    slug: "ufg-abre-vagas-novos-cursos",
    summary: "Instituição vai criar cursos de Engenharia de Dados, Medicina Veterinária e Fisioterapia em novas unidades regionais.",
    content: `<p>A Universidade Federal de Goiás anunciou a criação de 1.200 novas vagas em cursos de graduação a partir do segundo semestre de 2025, incluindo Engenharia de Dados, Medicina Veterinária e Fisioterapia.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['politica'],
    author: "Ana Souza",
    publishedAt: "2025-02-28T10:00:00",
    updatedAt:  "2025-02-28T10:00:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },
  {
    id: "13",
    title: "Deputados aprovam criação do Fundo Estadual de Meio Ambiente",
    slug: "deputados-aprovam-fundo-estadual-meio-ambiente",
    summary: "Recurso de R$ 400 milhões será destinado à recuperação de áreas degradadas e conservação do cerrado.",
    content: `<p>A Assembleia Legislativa aprovou a criação do Fundo Estadual de Meio Ambiente, com dotação inicial de R$ 400 milhões para projetos de recuperação do cerrado goiano.</p><p>Os recursos virão de royalties de mineração e de multas ambientais aplicadas pelo estado.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['politica'],
    author: "Maria Santos",
    publishedAt: "2025-02-27T11:00:00",
    updatedAt:  "2025-02-27T11:00:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },
  {
    id: "14",
    title: "Goiás integra rede nacional de cidades inteligentes",
    slug: "goias-integra-rede-cidades-inteligentes",
    summary: "Goiânia, Anápolis e Aparecida receberão infraestrutura de sensores urbanos e plataforma de gestão de dados.",
    content: `<p>Três cidades goianas foram selecionadas para integrar o Programa Nacional de Cidades Inteligentes do Ministério das Cidades, recebendo investimentos em sensores urbanos, câmeras inteligentes e plataforma integrada de gestão.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['politica'],
    author: "Carlos Lima",
    publishedAt: "2025-02-26T09:00:00",
    updatedAt:  "2025-02-26T09:00:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },
  {
    id: "15",
    title: "Secretaria de Saúde amplia rede de UPAs no interior do estado",
    slug: "secretaria-saude-amplia-upas-interior",
    summary: "Quatro novas Unidades de Pronto Atendimento serão inauguradas em cidades com mais de 50 mil habitantes.",
    content: `<p>A Secretaria de Estado da Saúde de Goiás anunciou a construção de quatro novas UPAs em Caldas Novas, Itumbiara, Luziânia e Formosa, beneficiando uma população total de 380 mil pessoas.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['politica'],
    author: "Pedro Alves",
    publishedAt: "2025-02-25T08:00:00",
    updatedAt:  "2025-02-25T08:00:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },
  {
    id: "16",
    title: "Programa Goiás Digital leva internet gratuita a 500 escolas rurais",
    slug: "programa-goias-digital-internet-escolas-rurais",
    summary: "Iniciativa do governo estadual garante conexão de alta velocidade em unidades de ensino da zona rural até dezembro.",
    content: `<p>O programa Goiás Digital vai instalar internet de fibra óptica em 500 escolas rurais do estado até dezembro de 2025, beneficiando 85 mil alunos e 6 mil professores.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1497864149936-d3163f0c0f4b?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['politica'],
    author: "Ana Souza",
    publishedAt: "2025-02-24T10:00:00",
    updatedAt:  "2025-02-24T10:00:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },
  {
    id: "17",
    title: "Governo estadual lança plano de combate às enchentes em regiões de risco",
    slug: "governo-plano-combate-enchentes-regioes-risco",
    summary: "Mapeamento identificou 180 áreas vulneráveis em 45 municípios goianos com histórico de inundações.",
    content: `<p>O Plano Estadual de Prevenção a Desastres Naturais vai atuar em 45 municípios goianos com histórico de enchentes, investindo em obras de drenagem, remoção de famílias em área de risco e sistemas de alerta precoce.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1547683905-f686c993aae5?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['politica'],
    author: "Maria Santos",
    publishedAt: "2025-02-23T09:00:00",
    updatedAt:  "2025-02-23T09:00:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },
  {
    id: "18",
    title: "Aprovado projeto de lei que cria carreira de assistente social nas escolas estaduais",
    slug: "projeto-carreira-assistente-social-escolas",
    summary: "Lei determina a contratação de um assistente social para cada 500 alunos matriculados na rede pública estadual.",
    content: `<p>A Assembleia Legislativa aprovou por unanimidade projeto que cria a carreira de assistente social nas escolas estaduais goianas, com um profissional para cada 500 alunos matriculados.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1509062522246-3755977927d7?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['politica'],
    author: "Carlos Lima",
    publishedAt: "2025-02-22T11:00:00",
    updatedAt:  "2025-02-22T11:00:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },
  {
    id: "19",
    title: "Prefeitura inaugura centro de referência para pessoas em situação de rua",
    slug: "prefeitura-inaugura-centro-referencia-situacao-rua",
    summary: "Espaço em Goiânia oferece acolhimento, atendimento psicossocial, documentação e encaminhamento ao trabalho.",
    content: `<p>A Prefeitura de Goiânia inaugurou o Centro de Referência Especializado para População em Situação de Rua, com capacidade para atender 200 pessoas por dia, oferecendo documentação, atendimento médico e psicossocial.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['politica'],
    author: "Pedro Alves",
    publishedAt: "2025-02-21T10:00:00",
    updatedAt:  "2025-02-21T10:00:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },
  {
    id: "20",
    title: "Goiás aprova política estadual de segurança alimentar e nutricional",
    slug: "goias-aprova-politica-seguranca-alimentar",
    summary: "Lei garante articulação entre secretarias para combater a fome e a insegurança alimentar no estado.",
    content: `<p>O governo de Goiás sancionou a Política Estadual de Segurança Alimentar e Nutricional, criando um conselho intersetorial para articular ações de combate à fome com participação de 12 secretarias estaduais.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1490818387583-1baba5e638af?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['politica'],
    author: "Ana Souza",
    publishedAt: "2025-02-20T09:00:00",
    updatedAt:  "2025-02-20T09:00:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },

  // ── ECONOMIA (20 notícias) ─────────────────────────────────────────
  {
    id: "21",
    title: "Banco Central reduz taxa de juros pela terceira vez consecutiva",
    slug: "banco-central-reduz-taxa-juros",
    summary: "Decisão unânime do Copom leva a Selic a 10,5% ao ano, menor patamar em dois anos.",
    content: `<p>O Copom decidiu por unanimidade reduzir a taxa Selic em 0,5 ponto percentual, levando-a para 10,5% ao ano. O Ibovespa fechou em alta de 1,8% e o dólar recuou para R$ 4,85.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['economia'],
    author: "Carlos Lima",
    publishedAt: "2025-03-09T14:30:00",
    updatedAt:  "2025-03-09T14:30:00",
    isPublished: true,
    isHighlight: true,
    isEditorial: true, 
    tags: []
  },
  {
    id: "22",
    title: "Agronegócio goiano bate recorde de exportações no primeiro trimestre",
    slug: "agronegocio-goiano-recorde-exportacoes",
    summary: "Soja, milho e carne bovina puxaram crescimento de 18% nas vendas externas.",
    content: `<p>O agronegócio de Goiás registrou US$ 4,2 bilhões em exportações no primeiro trimestre de 2025, crescimento de 18% sobre o mesmo período do ano anterior, liderado por soja (42%), milho (23%) e carne bovina (18%).</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['economia'],
    author: "Carlos Lima",
    publishedAt: "2025-03-06T10:00:00",
    updatedAt:  "2025-03-06T10:00:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },
  {
    id: "23",
    title: "Desemprego em Goiás cai para 6,2% e atinge menor nível histórico",
    slug: "desemprego-goias-cai-menor-nivel",
    summary: "Dado da PNAD Contínua mostra que estado tem a segunda menor taxa de desocupação do Centro-Oeste.",
    content: `<p>A taxa de desemprego em Goiás recuou para 6,2% no quarto trimestre de 2024, o menor nível desde 2012. Os setores que mais criaram vagas foram agronegócio, construção civil e comércio varejista.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['economia'],
    author: "Ana Souza",
    publishedAt: "2025-03-05T09:00:00",
    updatedAt:  "2025-03-05T09:00:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },
  {
    id: "24",
    title: "Startup goiana capta R$ 120 milhões para expandir tecnologia no agro",
    slug: "startup-goiana-capta-120-milhoes-agro",
    summary: "Empresa de Anápolis desenvolve monitoramento de lavouras por satélite e já atua em 8 estados.",
    content: `<p>A AgroSat, de Anápolis, captou R$ 120 milhões em rodada Série B e planeja expandir para todos os estados produtores até 2026, além de iniciar operações no Paraguai e na Argentina.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['economia'],
    author: "Pedro Alves",
    publishedAt: "2025-03-04T11:00:00",
    updatedAt:  "2025-03-04T11:00:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },
  {
    id: "25",
    title: "Goiás atrai R$ 3,8 bilhões em novos investimentos industriais",
    slug: "goias-atrai-investimentos-industriais",
    summary: "Setor automotivo e de alimentos lideram anúncios de novas fábricas no estado para 2025 e 2026.",
    content: `<p>O estado de Goiás atraiu R$ 3,8 bilhões em novos investimentos industriais anunciados no primeiro trimestre de 2025. Uma montadora de veículos elétricos e duas grandes indústrias de alimentos estão entre os destaques.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1565043666747-69f6646db940?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['economia'],
    author: "Carlos Lima",
    publishedAt: "2025-03-03T10:00:00",
    updatedAt:  "2025-03-03T10:00:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },
  {
    id: "26",
    title: "Comércio varejista de Goiânia registra alta de 8,3% em fevereiro",
    slug: "comercio-varejista-goiania-alta-fevereiro",
    summary: "Crescimento foi puxado pelas vendas de eletrodomésticos, vestuário e material de construção.",
    content: `<p>O comércio varejista de Goiânia registrou crescimento de 8,3% em fevereiro em comparação ao mesmo mês de 2024, segundo dados do IBGE, com destaque para eletrodomésticos (+14%) e vestuário (+11%).</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['economia'],
    author: "Ana Souza",
    publishedAt: "2025-03-02T09:00:00",
    updatedAt:  "2025-03-02T09:00:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },
  {
    id: "27",
    title: "Construção civil goiana cria 12 mil empregos no primeiro bimestre",
    slug: "construcao-civil-goiana-empregos",
    summary: "Setor é o que mais gerou postos de trabalho formal no estado nos dois primeiros meses do ano.",
    content: `<p>A construção civil gerou 12 mil novos empregos formais em Goiás no primeiro bimestre de 2025, tornando-se o setor com maior criação de postos de trabalho no estado no período, segundo o Caged.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['economia'],
    author: "Pedro Alves",
    publishedAt: "2025-03-01T08:00:00",
    updatedAt:  "2025-03-01T08:00:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },
  {
    id: "28",
    title: "Inflação em Goiânia fica em 0,38% em fevereiro, abaixo da média nacional",
    slug: "inflacao-goiania-fevereiro",
    summary: "Alimentação fora do domicílio e habitação foram os grupos que mais pressionaram o índice no mês.",
    content: `<p>O IPCA de Goiânia ficou em 0,38% em fevereiro, abaixo da média nacional de 0,44%. O acumulado dos últimos 12 meses é de 4,1%, dentro do teto da meta de inflação do Banco Central.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['economia'],
    author: "Carlos Lima",
    publishedAt: "2025-02-28T10:00:00",
    updatedAt:  "2025-02-28T10:00:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },
  {
    id: "29",
    title: "Polo tecnológico de Anápolis recebe 15 novas empresas em 2025",
    slug: "polo-tecnologico-anapolis-novas-empresas",
    summary: "Distrito Agroindustrial de Anápolis se consolida como segundo maior polo empresarial do Centro-Oeste.",
    content: `<p>O Distrito Agroindustrial de Anápolis (DAIA) recebeu 15 novas empresas em 2025, consolidando-se como o segundo maior polo empresarial do Centro-Oeste. O investimento total das novas instalações soma R$ 890 milhões.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['economia'],
    author: "Ana Souza",
    publishedAt: "2025-02-27T09:00:00",
    updatedAt:  "2025-02-27T09:00:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },
  {
    id: "30",
    title: "Turismo em Goiás cresce 22% e bate recorde de visitantes",
    slug: "turismo-goias-cresce-recorde-visitantes",
    summary: "Chapada dos Veadeiros, Pirenópolis e Caldas Novas lideram os destinos mais procurados no estado.",
    content: `<p>O turismo em Goiás registrou crescimento de 22% no número de visitantes em 2024, totalizando 8,4 milhões de turistas e gerando R$ 4,1 bilhões em receita. Chapada dos Veadeiros e Pirenópolis foram os destinos mais visitados.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['economia'],
    author: "Pedro Alves",
    publishedAt: "2025-02-26T10:00:00",
    updatedAt:  "2025-02-26T10:00:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },
  {
    id: "31",
    title: "Saúde: Goiás amplia programa de cirurgias eletivas e zera fila em 12 municípios",
    slug: "goias-amplia-cirurgias-eletivas-zera-fila",
    summary: "Estado realizou 48 mil procedimentos em 90 dias, reduzindo em 60% a lista de espera geral.",
    content: `<p>O mutirão de cirurgias eletivas realizou 48 mil procedimentos em 90 dias, zerando a fila em 12 municípios e reduzindo em 60% a lista de espera geral do estado.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1551190822-a9333d879b1f?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['economia'],
    author: "Carlos Lima",
    publishedAt: "2025-02-25T08:00:00",
    updatedAt:  "2025-02-25T08:00:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },
  {
    id: "32",
    title: "Exportações de carne bovina goiana batem recorde histórico",
    slug: "exportacoes-carne-bovina-goiana-recorde",
    summary: "Estado enviou 180 mil toneladas de carne para 65 países em 2024, aumento de 24% sobre o ano anterior.",
    content: `<p>Goiás exportou 180 mil toneladas de carne bovina em 2024, volume recorde que representa crescimento de 24% sobre 2023. China, Estados Unidos e União Europeia são os principais compradores.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['economia'],
    author: "Ana Souza",
    publishedAt: "2025-02-24T09:00:00",
    updatedAt:  "2025-02-24T09:00:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },
  {
    id: "33",
    title: "Bancos registram aumento de 15% na concessão de crédito em Goiás",
    slug: "bancos-aumento-credito-goias",
    summary: "Crédito para pessoa física e para o agronegócio lideraram o crescimento no primeiro trimestre.",
    content: `<p>A concessão de crédito bancário em Goiás cresceu 15% no primeiro trimestre de 2025, impulsionada pela redução da taxa Selic. O crédito rural e o financiamento habitacional tiveram os maiores aumentos.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['economia'],
    author: "Pedro Alves",
    publishedAt: "2025-02-23T10:00:00",
    updatedAt:  "2025-02-23T10:00:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },
  {
    id: "34",
    title: "Energia solar em Goiás supera 2 gigawatts de capacidade instalada",
    slug: "energia-solar-goias-capacidade-instalada",
    summary: "Estado é o quarto maior produtor de energia solar do Brasil e mira liderança regional até 2027.",
    content: `<p>Goiás atingiu 2,1 gigawatts de capacidade instalada de energia solar fotovoltaica, tornando-se o quarto maior produtor nacional. O estado conta com mais de 180 mil sistemas instalados em residências, comércios e indústrias.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1509391366360-2e959784a276?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['economia'],
    author: "Carlos Lima",
    publishedAt: "2025-02-22T09:00:00",
    updatedAt:  "2025-02-22T09:00:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },
  {
    id: "35",
    title: "Mercado imobiliário de Goiânia valoriza 18% em 2024",
    slug: "mercado-imobiliario-goiania-valoriza",
    summary: "Alta nos preços dos imóveis é puxada pela demanda crescente e pela chegada de novos empreendimentos.",
    content: `<p>O mercado imobiliário de Goiânia registrou valorização média de 18% nos preços dos imóveis residenciais em 2024, com os bairros Jardim Goiás e Bueno liderando a alta. Foram lançados 14.200 unidades no ano.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['economia'],
    author: "Ana Souza",
    publishedAt: "2025-02-21T10:00:00",
    updatedAt:  "2025-02-21T10:00:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },
  {
    id: "36",
    title: "Fintechs goianas movimentam R$ 2,3 bilhões em transações em 2024",
    slug: "fintechs-goianas-transacoes-2024",
    summary: "Ecossistema de startups financeiras do estado cresceu 40% e já emprega 3.200 profissionais.",
    content: `<p>As fintechs sediadas em Goiás movimentaram R$ 2,3 bilhões em transações em 2024, crescimento de 40% sobre o ano anterior. O ecossistema reúne 85 empresas e emprega mais de 3.200 profissionais qualificados.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1563986768609-322da13575f3?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['economia'],
    author: "Pedro Alves",
    publishedAt: "2025-02-20T08:00:00",
    updatedAt:  "2025-02-20T08:00:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },
  {
    id: "37",
    title: "Cadeia produtiva do etanol em Goiás gera 180 mil empregos diretos",
    slug: "cadeia-produtiva-etanol-goias-empregos",
    summary: "Estado é o segundo maior produtor nacional de etanol e cana-de-açúcar, atrás apenas de São Paulo.",
    content: `<p>O setor sucroenergético de Goiás emprega 180 mil pessoas diretamente e movimenta R$ 28 bilhões por ano, segundo levantamento da Sifaeg. O estado opera 36 usinas de processamento de cana-de-açúcar.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['economia'],
    author: "Carlos Lima",
    publishedAt: "2025-02-19T09:00:00",
    updatedAt:  "2025-02-19T09:00:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },
  {
    id: "38",
    title: "Goiás recebe certificação de hub logístico do Centro-Oeste",
    slug: "goias-hub-logistico-centro-oeste",
    summary: "Posição geográfica privilegiada e infraestrutura de rodovias e ferrovias atraem centros de distribuição.",
    content: `<p>A posição central de Goiás no território brasileiro e sua malha de rodovias federais consolidam o estado como principal hub logístico do Centro-Oeste, com 45 grandes centros de distribuição instalados nos últimos três anos.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['economia'],
    author: "Ana Souza",
    publishedAt: "2025-02-18T10:00:00",
    updatedAt:  "2025-02-18T10:00:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },
  {
    id: "39",
    title: "Pequenas empresas goianas crescem 12% e batem recorde de abertura",
    slug: "pequenas-empresas-goianas-crescem",
    summary: "Mais de 48 mil novos CNPJs foram abertos no estado em 2024, com destaque para serviços e comércio.",
    content: `<p>Goiás registrou a abertura de 48.200 novas empresas em 2024, recorde histórico e crescimento de 12% sobre 2023. O setor de serviços respondeu por 62% dos novos registros.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['economia'],
    author: "Pedro Alves",
    publishedAt: "2025-02-17T09:00:00",
    updatedAt:  "2025-02-17T09:00:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },
  {
    id: "40",
    title: "Investimentos em infraestrutura hídrica garantem abastecimento até 2040",
    slug: "investimentos-infraestrutura-hidrica-abastecimento",
    summary: "Obras de ampliação de reservatórios e modernização do sistema de saneamento asseguram água para 4 milhões de goianos.",
    content: `<p>O programa de investimentos em infraestrutura hídrica de Goiás, com R$ 1,8 bilhão em obras até 2027, garantirá o abastecimento de água para 4 milhões de pessoas nas regiões metropolitanas até 2040.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1468421201266-ec88b2809284?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['economia'],
    author: "Carlos Lima",
    publishedAt: "2025-02-16T08:00:00",
    updatedAt:  "2025-02-16T08:00:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },

  // ── ESPORTE (15 notícias) ──────────────────────────────────────────
  {
    id: "41",
    title: "Goiás vence o Atlético-MG de virada e avança na Copa do Brasil",
    slug: "goias-vence-atletico-mg-copa-brasil",
    summary: "Esmeraldino virou o jogo nos acréscimos com dois gols de Alesson e garantiu vaga nas oitavas.",
    content: `<p>Em uma noite épica no Serrinha, o Goiás virou o jogo contra o Atlético Mineiro por 2 a 1 nos acréscimos, com dois gols de Alesson. Nas oitavas, o Esmeraldino enfrenta o Fluminense.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['esporte'],
    author: "Pedro Alves",
    publishedAt: "2025-03-10T22:30:00",
    updatedAt:  "2025-03-10T22:30:00",
    isPublished: true,
    isHighlight: true,
    isEditorial: true, 
    tags: []
  },
  {
    id: "42",
    title: "Atlético Goianiense anuncia contratação de atacante uruguaio",
    slug: "atletico-goianiense-contratacao-atacante-uruguaio",
    summary: "Rodrigo Bentancourt, 26 anos, chega por empréstimo do Nacional de Montevidéu até dezembro.",
    content: `<p>O Atlético Goianiense confirmou a contratação do atacante Rodrigo Bentancourt, 26 anos, do Nacional de Montevidéu. O atleta marcou 14 gols em 22 jogos no último campeonato uruguaio.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1543326727-cf6c39e8f84c?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['esporte'],
    author: "Pedro Alves",
    publishedAt: "2025-03-08T16:00:00",
    updatedAt:  "2025-03-08T16:00:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },
  {
    id: "43",
    title: "Atleta goiana conquista ouro no Pan-Americano de natação",
    slug: "atleta-goiana-ouro-pan-americano-natacao",
    summary: "Isabela Ferreira, 19 anos, quebrou o recorde pan-americano nos 200m borboleta em Lima.",
    content: `<p>A nadadora goiana Isabela Ferreira conquistou o ouro nos 200m borboleta no Pan-Americano em Lima, com tempo de 2min04s32, novo recorde continental. Ela tem vaga garantida nos Olímpicos de 2028.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1530549387789-4c1017266635?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['esporte'],
    author: "Ana Souza",
    publishedAt: "2025-03-07T19:00:00",
    updatedAt:  "2025-03-07T19:00:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },
  {
    id: "44",
    title: "Goiânia confirma sede da Copa América Feminina 2026",
    slug: "goiania-sede-copa-america-feminina-2026",
    summary: "Serra Dourada passará por reforma de R$ 85 milhões para receber ao menos 4 partidas do torneio.",
    content: `<p>A Conmebol confirmou Goiânia como sede da Copa América Feminina 2026. O Serra Dourada passará por reforma de R$ 85 milhões com conclusão prevista para março de 2026.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1489944440615-453fc2b6a9a9?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['esporte'],
    author: "Carlos Lima",
    publishedAt: "2025-03-05T10:00:00",
    updatedAt:  "2025-03-05T10:00:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },
  {
    id: "45",
    title: "Vilanova FC de Aparecida sobe para a Série C do Campeonato Brasileiro",
    slug: "vilanova-fc-sobe-serie-c",
    summary: "Clube conquista acesso inédito após campanha histórica no Campeonato Goiano e na Série D.",
    content: `<p>O Vilanova Futebol Clube, de Aparecida de Goiânia, conquistou o acesso inédito à Série C do Campeonato Brasileiro após vencer o confronto decisivo por 2 a 0. A torcida comemorou nas ruas da cidade.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1459865264687-595d652de67e?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['esporte'],
    author: "Pedro Alves",
    publishedAt: "2025-03-04T21:00:00",
    updatedAt:  "2025-03-04T21:00:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },
  {
    id: "46",
    title: "Judoca goiano é convocado para o Grand Slam de Paris",
    slug: "judoca-goiano-convocado-grand-slam-paris",
    summary: "Marcus Vinicius Silva, campeão sul-americano, representará o Brasil no torneio mais importante do calendário.",
    content: `<p>O judoca goiano Marcus Vinicius Silva, campeão sul-americano na category até 81kg, foi convocado pela Confederação Brasileira de Judô para o Grand Slam de Paris, principal etapa do circuito mundial.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['esporte'],
    author: "Ana Souza",
    publishedAt: "2025-03-03T10:00:00",
    updatedAt:  "2025-03-03T10:00:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },
  {
    id: "47",
    title: "Goiás recebe etapa do Circuito Nacional de Vôlei de Praia",
    slug: "goias-etapa-circuito-volei-praia",
    summary: "Evento acontece em Caldas Novas com participação de duplas do ranking nacional e internacional.",
    content: `<p>Caldas Novas sediará etapa do Circuito Nacional de Vôlei de Praia nos dias 15 e 16 de março, com a participação de 32 duplas masculinas e 28 femininas do ranking nacional, além de convidados internacionais.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1612872087720-bb876e2e67d1?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['esporte'],
    author: "Pedro Alves",
    publishedAt: "2025-03-02T09:00:00",
    updatedAt:  "2025-03-02T09:00:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },
  {
    id: "48",
    title: "Programa de base do Goiás EC forma 12 jogadores profissionais em 2024",
    slug: "base-goias-ec-jogadores-profissionais",
    summary: "category sub-20 do Esmeraldino é a que mais revelou atletas para times profissionais no Centro-Oeste.",
    content: `<p>O programa de base do Goiás Esporte Clube formou 12 jogadores que assinaram contratos profissionais em 2024, tornando-se a category reveladora mais produtiva do Centro-Oeste no ano.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['esporte'],
    author: "Carlos Lima",
    publishedAt: "2025-03-01T08:00:00",
    updatedAt:  "2025-03-01T08:00:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },
  {
    id: "49",
    title: "Tenista goiana sobe 40 posições no ranking da WTA",
    slug: "tenista-goiana-sobe-ranking-wta",
    summary: "Camila Borges, de Rio Verde, alcança a posição 180 do mundo após título em torneio ITF na Europa.",
    content: `<p>A tenista Camila Borges, natural de Rio Verde, subiu 40 posições no ranking da WTA após conquistar seu segundo título em torneio ITF na Europa. Ela está na posição 180 do mundo e mira o Top 100.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1554068865-24cecd4e34b8?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['esporte'],
    author: "Ana Souza",
    publishedAt: "2025-02-28T10:00:00",
    updatedAt:  "2025-02-28T10:00:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },
  {
    id: "50",
    title: "Maratona de Goiânia bate recorde com 18 mil inscritos",
    slug: "maratona-goiania-recorde-inscritos",
    summary: "Edição deste ano terá largada na Avenida Goiás e percurso pelo centro histórico da capital.",
    content: `<p>A Maratona Internacional de Goiânia 2025 bateu recorde de inscrições com 18 mil participantes, sendo 3.200 estrangeiros de 42 países. A prova ocorre em maio com largada na Avenida Goiás.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1452626038306-9aae5e071dd3?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['esporte'],
    author: "Pedro Alves",
    publishedAt: "2025-02-27T09:00:00",
    updatedAt:  "2025-02-27T09:00:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },
  {
    id: "51",
    title: "Natação goiana conquista 8 medalhas no Troféu Brasil",
    slug: "natacao-goiana-medalhas-trofeu-brasil",
    summary: "Delegação do estado foi a terceira mais premiada na competição que reuniu os melhores nadadores do país.",
    content: `<p>A delegação goiana de natação conquistou 8 medalhas no Troféu Brasil — 3 ouros, 3 pratas e 2 bronzes — tornando-se a terceira força do país na competição realizada em São Paulo.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1519315901367-f34ff9154487?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['esporte'],
    author: "Carlos Lima",
    publishedAt: "2025-02-26T10:00:00",
    updatedAt:  "2025-02-26T10:00:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },
  {
    id: "52",
    title: "Goiás sedia pela primeira vez etapa do Campeonato Brasileiro de Ciclismo",
    slug: "goias-etapa-campeonato-brasileiro-ciclismo",
    summary: "Percurso passará pela Chapada dos Veadeiros e terá largada em Alto Paraíso em setembro.",
    content: `<p>A Confederação Brasileira de Ciclismo anunciou que Goiás sediará uma etapa do Campeonato Brasileiro pela primeira vez, com percurso de 180 km pela Chapada dos Veadeiros em setembro.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['esporte'],
    author: "Ana Souza",
    publishedAt: "2025-02-25T08:00:00",
    updatedAt:  "2025-02-25T08:00:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },
  {
    id: "53",
    title: "Academia de boxe goiana revela campeão sul-americano juvenil",
    slug: "academia-boxe-goiana-campeao-sul-americano",
    summary: "Lucas Mendonça, 17 anos, de Trindade, vence torneio em Buenos Aires e mira o Pan-Americano.",
    content: `<p>Lucas Mendonça, 17 anos, de Trindade, foi campeão sul-americano juvenil de boxe na category até 60kg, vencendo por pontos na final em Buenos Aires. O jovem treina desde os 9 anos na Academia Garra.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1549719386-74dfcbf7dbed?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['esporte'],
    author: "Pedro Alves",
    publishedAt: "2025-02-24T09:00:00",
    updatedAt:  "2025-02-24T09:00:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },
  {
    id: "54",
    title: "Estádio Olímpico passa por reforma de gramado e vestiários",
    slug: "estadio-olimpico-reforma-gramado-vestiarios",
    summary: "Obras custam R$ 12 milhões e devem ser concluídas antes do início do Campeonato Goiano.",
    content: `<p>O Estádio Olímpico Pedro Ludovico Teixeira está passando por reforma de R$ 12 milhões, com troca total do gramado, modernização dos vestiários e instalação de novo sistema de iluminação LED.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1540747913346-19212a4b423e?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['esporte'],
    author: "Carlos Lima",
    publishedAt: "2025-02-23T10:00:00",
    updatedAt:  "2025-02-23T10:00:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },
  {
    id: "55",
    title: "Goiás conquista quatro vagas nos Jogos Escolares Nacionais",
    slug: "goias-vagas-jogos-escolares-nacionais",
    summary: "Estudantes-atletas do estado se destacaram no atletismo, natação, futsal e ginástica artística.",
    content: `<p>Goiás conquistou quatro vagas nos Jogos Escolares Nacionais, com estudantes-atletas se classificando no atletismo, natação, futsal feminino e ginástica artística. A delegação viaja para Brasília em julho.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['esporte'],
    author: "Ana Souza",
    publishedAt: "2025-02-22T09:00:00",
    updatedAt:  "2025-02-22T09:00:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },

  // ── ENTRETENIMENTO (15 notícias) ──────────────────────────────────
  {
    id: "56",
    title: "Festival de música de Goiânia anuncia line-up com Ivete Sangalo e Criolo",
    slug: "festival-musica-goiania-lineup-ivete-criolo",
    summary: "FestGoiânia 2025 acontece em junho no Parque Vaca Brava e espera reunir 80 mil pessoas.",
    content: `<p>O FestGoiânia 2025 acontece de 13 a 15 de junho no Parque Vaca Brava com Ivete Sangalo, Criolo e Seu Jorge como headliners. Os ingressos custam R$ 380 o passaporte para os três dias.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['entretenimento'],
    author: "Maria Santos",
    publishedAt: "2025-03-10T12:00:00",
    updatedAt:  "2025-03-10T12:00:00",
    isPublished: true,
    isHighlight: true,
    isEditorial: true, 
    tags: []
  },
  {
    id: "57",
    title: "Série brasileira gravada em Goiás estreia na Netflix e entra no top 10 mundial",
    slug: "serie-brasileira-goias-netflix-top-10",
    summary: "Produção ambientada no cerrado goiano acumula 12 milhões de visualizações na primeira semana.",
    content: `<p>A série "Cerrado", filmada na Chapada dos Veadeiros e em Pirenópolis, estreou na Netflix e entrou no top 10 em 14 países. Uma segunda temporada já foi confirmada.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['entretenimento'],
    author: "Pedro Alves",
    publishedAt: "2025-03-09T09:00:00",
    updatedAt:  "2025-03-09T09:00:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },
  {
    id: "58",
    title: "Museu de Arte de Goiânia reabre após reforma com exposição inédita",
    slug: "museu-arte-goiania-reabre-exposicao",
    summary: "MAG ganha 2.400 m² e inaugura mostra sobre arte contemporânea do cerrado com 80 obras.",
    content: `<p>O MAG reabriu após 18 meses de reforma com a exposição "Cerrado Vivo", com 80 obras de artistas do Centro-Oeste. A entrada é gratuita nos primeiros 30 dias.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1565060169194-19fabf63012c?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['entretenimento'],
    author: "Ana Souza",
    publishedAt: "2025-03-08T10:00:00",
    updatedAt:  "2025-03-08T10:00:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },
  {
    id: "59",
    title: "Peça teatral goiana ganha prêmio nacional e faz turnê em 10 cidades",
    slug: "peca-teatral-goiana-premio-nacional",
    summary: "Espetáculo 'Raízes do Sertão' venceu o Prêmio FUNARTE de Teatro 2025 em quatro categorys.",
    content: `<p>A Companhia Anhanguera venceu o Prêmio FUNARTE 2025 com "Raízes do Sertão", conquistando melhor espetáculo, direção, cenografia e trilha sonora. A turnê passa por 10 capitais.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1503095396549-807759245b35?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['entretenimento'],
    author: "Maria Santos",
    publishedAt: "2025-03-06T14:00:00",
    updatedAt:  "2025-03-06T14:00:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },
  {
    id: "60",
    title: "Chapada dos Veadeiros recebe certificação de parque mais sustentável do Brasil",
    slug: "chapada-veadeiros-certificacao-sustentavel",
    summary: "Reconhecimento internacional destaca práticas de conservação e turismo responsável.",
    content: `<p>O Parque Nacional da Chapada dos Veadeiros recebeu do IUCN o certificado de parque mais sustentável do Brasil, abrigando 2.600 espécies de plantas e 800 de animais vertebrados.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['entretenimento'],
    author: "Pedro Alves",
    publishedAt: "2025-03-06T08:00:00",
    updatedAt:  "2025-03-06T08:00:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },
  {
    id: "61",
    title: "Goiânia recebe edição especial da Bienal do Livro com 400 expositores",
    slug: "goiania-bienal-livro-400-expositores",
    summary: "Evento ocorre no Centro de Convenções e espera receber 200 mil visitantes ao longo de 10 dias.",
    content: `<p>A Bienal do Livro de Goiânia 2025 reúne 400 expositores de todo o Brasil no Centro de Convenções, com programação de lançamentos, bate-papos com authores e espaço kids especial.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['entretenimento'],
    author: "Ana Souza",
    publishedAt: "2025-03-05T10:00:00",
    updatedAt:  "2025-03-05T10:00:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },
  {
    id: "62",
    title: "Cineastas goianos vencem festival internacional de curtas em Berlim",
    slug: "cineastas-goianos-festival-berlim",
    summary: "Filme 'Vereda' retrata a vida de garimpeiros no interior de Goiás e conquista júri europeu.",
    content: `<p>O curta-metragem "Vereda", dirigido pela cineasta goiana Rafaela Pimentel, venceu o prêmio de melhor filme estrangeiro no Festival de Berlim na category curtas. A obra retrata garimpeiros de Minaçu.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['entretenimento'],
    author: "Maria Santos",
    publishedAt: "2025-03-04T11:00:00",
    updatedAt:  "2025-03-04T11:00:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },
  {
    id: "63",
    title: "Show de Djavan em Goiânia esgota ingressos em 2 horas",
    slug: "show-djavan-goiania-ingressos-esgotam",
    summary: "Apresentação ocorre em julho no Goiânia Arena e já tem segunda data confirmada pela produção.",
    content: `<p>Os ingressos para o show de Djavan em Goiânia esgotaram em menos de duas horas após abertura de vendas, obrigando a produção a confirmar uma segunda apresentação no mesmo local.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['entretenimento'],
    author: "Pedro Alves",
    publishedAt: "2025-03-03T09:00:00",
    updatedAt:  "2025-03-03T09:00:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },
  {
    id: "64",
    title: "Banda goiana 'Cerrado Sessions' estreia álbum nas plataformas digitais",
    slug: "banda-cerrado-sessions-album-plataformas",
    summary: "Trabalho mistura rock alternativo com influências do folk do interior goiano e ganhou críticas positivas.",
    content: `<p>A banda goiana Cerrado Sessions lançou seu primeiro álbum "Veredas", com 12 faixas que mesclam rock alternativo com referências musicais do interior de Goiás. O trabalho recebeu críticas muito positivas.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['entretenimento'],
    author: "Ana Souza",
    publishedAt: "2025-03-02T10:00:00",
    updatedAt:  "2025-03-02T10:00:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },
  {
    id: "65",
    title: "Centro Cultural de Goiânia lança programa de residências artísticas",
    slug: "centro-cultural-goiania-residencias-artisticas",
    summary: "Iniciativa oferece bolsas de R$ 4 mil mensais para artistas visuais, músicos e dramaturgos.",
    content: `<p>O Centro Cultural Oscar Niemeyer lança programa de residências artísticas com 20 bolsas de R$ 4 mil mensais para artistas de todo o Brasil que queiram desenvolver projetos em Goiânia por 3 meses.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['entretenimento'],
    author: "Maria Santos",
    publishedAt: "2025-03-01T08:00:00",
    updatedAt:  "2025-03-01T08:00:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },
  {
    id: "66",
    title: "Documentário sobre o cerrado goiano vence prêmio nacional de cinema",
    slug: "documentario-cerrado-goiano-premio-nacional",
    summary: "Obra foi produzida por realizadores de Goiânia e retrata a biodiversidade e cultura do bioma.",
    content: `<p>O documentário "Alma do Cerrado", produzido em Goiânia, venceu o Grande Prêmio do Cinema Brasileiro na category documentário de longa-metragem, sendo exibido em 12 países.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1440404653325-ab127d49abc1?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['entretenimento'],
    author: "Pedro Alves",
    publishedAt: "2025-02-28T10:00:00",
    updatedAt:  "2025-02-28T10:00:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },
  {
    id: "67",
    title: "Exposição de fotografia retrata 100 anos da imigração japonesa em Goiás",
    slug: "exposicao-fotografia-imigracao-japonesa-goias",
    summary: "Mostra reúne 150 imagens históricas e contemporâneas que celebram a contribuição da comunidade nipo-goiana.",
    content: `<p>A exposição "Raízes do Sol Nascente" comemora 100 anos da chegada dos primeiros imigrantes japoneses a Goiás com 150 fotografias que atravessam décadas de história e cultura.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['entretenimento'],
    author: "Ana Souza",
    publishedAt: "2025-02-27T09:00:00",
    updatedAt:  "2025-02-27T09:00:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },
  {
    id: "68",
    title: "Literatura goiana ganha espaço internacional com traduções para cinco idiomas",
    slug: "literatura-goiana-traducoes-cinco-idiomas",
    summary: "Três authores do estado tiveram obras adquiridas por editoras europeias e norte-americanas.",
    content: `<p>Três escritores goianos assinaram contratos com editoras internacionais para tradução de suas obras para inglês, francês, alemão, espanhol e italiano, ampliando o reconhecimento da literatura regional.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['entretenimento'],
    author: "Maria Santos",
    publishedAt: "2025-02-26T10:00:00",
    updatedAt:  "2025-02-26T10:00:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },
  {
    id: "69",
    title: "Pirenópolis recebe festival gastronômico com chefs de todo o Brasil",
    slug: "pirenopolis-festival-gastronomico",
    summary: "Evento de três dias reúne 40 chefs e celebra a cozinha goiana com ingredientes típicos do cerrado.",
    content: `<p>O Festival Gastronômico de Pirenópolis reúne 40 chefs de 18 estados para celebrar a cozinha do cerrado, com destaque para pequi, baru, lobeira e outros ingredientes nativos de Goiás.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['entretenimento'],
    author: "Pedro Alves",
    publishedAt: "2025-02-25T09:00:00",
    updatedAt:  "2025-02-25T09:00:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },
  {
    id: "70",
    title: "Companhia de dança goiana é convidada para temporada no Theatro Municipal de SP",
    slug: "companhia-danca-goiana-theatro-municipal-sp",
    summary: "Grupo Dança Cerrado apresentará espetáculo que mistura dança contemporânea com dança de fita.",
    content: `<p>A Companhia Dança Cerrado, de Goiânia, foi convidada para uma temporada de três semanas no Theatro Municipal de São Paulo com o espetáculo "Savana", que mistura dança contemporânea com dança de fita.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1518834107812-67b0b7c58434?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['entretenimento'],
    author: "Ana Souza",
    publishedAt: "2025-02-24T10:00:00",
    updatedAt:  "2025-02-24T10:00:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },

  // ── SEGURANÇA (15 notícias) ────────────────────────────────────────
  {
    id: "71",
    title: "Operação desmantela esquema de tráfico de drogas em Aparecida de Goiânia",
    slug: "operacao-desmantela-trafico-aparecida-goiania",
    summary: "Polícia Civil prendeu 12 suspeitos e apreendeu mais de 200 kg de entorpecentes em 48 horas.",
    content: `<p>A Operação Barreira prendeu 12 pessoas e apreendeu 210 kg de cocaína, 85 kg de maconha, R$ 340 mil em espécie e 15 armas em Aparecida de Goiânia. A organização movimentava R$ 2 milhões por mês.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['seguranca'],
    author: "Carlos Lima",
    publishedAt: "2025-03-10T06:00:00",
    updatedAt:  "2025-03-10T06:00:00",
    isPublished: true,
    isHighlight: true,
    isEditorial: true, 
    tags: []
  },
  {
    id: "72",
    title: "Goiás registra queda de 14% nos homicídios no primeiro bimestre de 2025",
    slug: "goias-queda-homicidios-primeiro-bimestre",
    summary: "SSP mostra queda de 312 para 268 mortes violentas em comparação com o mesmo período de 2024.",
    content: `<p>Os homicídios dolosos em Goiás caíram 14% no primeiro bimestre, de 312 para 268. Os roubos a veículos cresceram 8%, motivando reforço de efetivo nas rodovias do estado.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1453873531674-2151bcd01707?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['seguranca'],
    author: "Maria Santos",
    publishedAt: "2025-03-07T10:00:00",
    updatedAt:  "2025-03-07T10:00:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },
  {
    id: "73",
    title: "PM lança programa de policiamento comunitário em 20 bairros de Goiânia",
    slug: "pm-policiamento-comunitario-goiania",
    summary: "Iniciativa coloca 150 policiais em contato direto com moradores para prevenção de crimes.",
    content: `<p>O programa "PM na Comunidade" posiciona 150 policiais em 20 bairros de Goiânia para reuniões mensais com moradores, ações de prevenção e acompanhamento de demandas locais.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1609710228159-0fa9bd7c0827?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['seguranca'],
    author: "Pedro Alves",
    publishedAt: "2025-03-05T08:00:00",
    updatedAt:  "2025-03-05T08:00:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },
  {
    id: "74",
    title: "Fraude milionária em licitação é descoberta pela CGM de Goiânia",
    slug: "fraude-licitacao-cgm-goiania",
    summary: "Auditoria identificou superfaturamento de R$ 4,2 milhões em contratos de reforma de escolas.",
    content: `<p>A CGM de Goiânia identificou superfaturamento de R$ 4,2 milhões em contratos de reforma de 23 escolas municipais. Três servidores foram afastados e o caso foi encaminhado ao MP e à Polícia Civil.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['seguranca'],
    author: "Ana Souza",
    publishedAt: "2025-03-04T09:30:00",
    updatedAt:  "2025-03-04T09:30:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },
  {
    id: "75",
    title: "Polícia Civil prende quadrilha especializada em golpes digitais",
    slug: "policia-civil-prende-quadrilha-golpes-digitais",
    summary: "Grupo aplicava golpes do PIX e da falsa central bancária, causando prejuízo de R$ 8 milhões.",
    content: `<p>A Polícia Civil prendeu 9 integrantes de uma quadrilha especializada em golpes digitais que causou prejuízo de R$ 8 milhões a mais de 1.200 vítimas em Goiás e outros estados.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['seguranca'],
    author: "Carlos Lima",
    publishedAt: "2025-03-03T10:00:00",
    updatedAt:  "2025-03-03T10:00:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },
  {
    id: "76",
    title: "Detran-GO inicia operação especial de fiscalização nas rodovias estaduais",
    slug: "detran-go-operacao-fiscalizacao-rodovias",
    summary: "Ação prevê 120 pontos de controle em estradas goianas durante feriado prolongado de março.",
    content: `<p>O Detran-GO implantará 120 pontos de fiscalização nas principais rodovias estaduais durante o feriado prolongado, com foco em embriaguez ao volante, excesso de velocidade e uso do cinto de segurança.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['seguranca'],
    author: "Maria Santos",
    publishedAt: "2025-03-02T08:00:00",
    updatedAt:  "2025-03-02T08:00:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },
  {
    id: "77",
    title: "Sistema de câmeras inteligentes reduz assaltos em 30% no centro de Goiânia",
    slug: "cameras-inteligentes-reduz-assaltos-goiania",
    summary: "Tecnologia de reconhecimento facial ajudou a identificar e prender suspeitos em tempo real.",
    content: `<p>O sistema de câmeras inteligentes instalado no centro de Goiânia reduziu os assaltos em 30% nos primeiros seis meses de operação, com reconhecimento facial identificando suspeitos em tempo real.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1557804506-669a67965ba0?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['seguranca'],
    author: "Pedro Alves",
    publishedAt: "2025-03-01T09:00:00",
    updatedAt:  "2025-03-01T09:00:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },
  {
    id: "78",
    title: "Bombeiros realizam maior operação de resgate da história do estado",
    slug: "bombeiros-maior-operacao-resgate-goias",
    summary: "Equipes salvaram 340 pessoas durante enchentes que afetaram 12 municípios do sudoeste goiano.",
    content: `<p>O Corpo de Bombeiros Militar de Goiás realizou a maior operação de resgate da história do estado, salvando 340 pessoas durante as enchentes que atingiram 12 municípios do sudoeste goiano na última semana.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['seguranca'],
    author: "Ana Souza",
    publishedAt: "2025-02-28T10:00:00",
    updatedAt:  "2025-02-28T10:00:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },
  {
    id: "79",
    title: "Ministério Público denuncia 18 pessoas por desvio de verbas na saúde municipal",
    slug: "mp-denuncia-desvio-verbas-saude-municipal",
    summary: "Investigação apurou desvio de R$ 12 milhões em contratos de medicamentos e equipamentos hospitalares.",
    content: `<p>O Ministério Público de Goiás denunciou 18 pessoas, incluindo ex-secretários e empresários, por desvio de R$ 12 milhões em contratos de saúde de dois municípios do interior goiano.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['seguranca'],
    author: "Carlos Lima",
    publishedAt: "2025-02-27T09:00:00",
    updatedAt:  "2025-02-27T09:00:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },
  {
    id: "80",
    title: "Polícia Federal deflagra operação contra contrabando no sudoeste goiano",
    slug: "policia-federal-operacao-contrabando-sudoeste",
    summary: "Apreendidos cigarros, eletrônicos e agrotóxicos ilegais avaliados em R$ 15 milhões.",
    content: `<p>A Polícia Federal deflagrou operação contra uma rede de contrabando que atuava no sudoeste goiano, apreendendo R$ 15 milhões em mercadorias ilegais, incluindo cigarros, eletrônicos e agrotóxicos proibidos.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['seguranca'],
    author: "Maria Santos",
    publishedAt: "2025-02-26T08:00:00",
    updatedAt:  "2025-02-26T08:00:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },
  {
    id: "81",
    title: "Goiás inaugura primeira delegacia especializada em crimes ambientais",
    slug: "goias-delegacia-especializada-crimes-ambientais",
    summary: "Unidade em Goiânia terá equipe de 40 investigadores para apurar desmatamento e poluição.",
    content: `<p>A primeira Delegacia Especializada em Crimes Ambientais de Goiás foi inaugurada em Goiânia com uma equipe de 40 investigadores dedicados exclusivamente a apurar desmatamento, poluição e tráfico de fauna.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['seguranca'],
    author: "Pedro Alves",
    publishedAt: "2025-02-25T10:00:00",
    updatedAt:  "2025-02-25T10:00:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },
  {
    id: "82",
    title: "Trânsito: mortes em acidentes caem 18% nas rodovias goianas em 2024",
    slug: "transito-mortes-acidentes-rodovias-goianas",
    summary: "Resultado é atribuído às campanhas educativas, radares e reforço do policiamento rodoviário.",
    content: `<p>As mortes em acidentes de trânsito nas rodovias goianas caíram 18% em 2024, saindo de 1.240 para 1.018 óbitos. Campanhas educativas e novos radares são apontados como principais fatores.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['seguranca'],
    author: "Ana Souza",
    publishedAt: "2025-02-24T09:00:00",
    updatedAt:  "2025-02-24T09:00:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },
  {
    id: "83",
    title: "Operação prende quadrilha que fraudava o seguro DPVAT em Goiás",
    slug: "operacao-prende-quadrilha-fraude-dpvat",
    summary: "Grupo criava acidentes falsos para receber indenizações e causou prejuízo de R$ 3,2 milhões.",
    content: `<p>Uma quadrilha que criava acidentes de trânsito falsos para fraudar o seguro DPVAT foi desarticulada pela Polícia Civil em Goiás. O grupo causou prejuízo de R$ 3,2 milhões em dois anos de atuação.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['seguranca'],
    author: "Carlos Lima",
    publishedAt: "2025-02-23T10:00:00",
    updatedAt:  "2025-02-23T10:00:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },
  {
    id: "84",
    title: "Goiânia terá novo Centro Integrado de Segurança Pública em 2026",
    slug: "goiania-centro-integrado-seguranca-publica",
    summary: "Obra de R$ 45 milhões vai reunir PM, Bombeiros, SAMU e Defesa Civil em um único complexo.",
    content: `<p>Goiânia terá um Centro Integrado de Segurança Pública de R$ 45 milhões, reunindo Polícia Militar, Bombeiros, SAMU e Defesa Civil em um único complexo com sala de monitoramento 24 horas.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['seguranca'],
    author: "Maria Santos",
    publishedAt: "2025-02-22T09:00:00",
    updatedAt:  "2025-02-22T09:00:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },
  {
    id: "85",
    title: "Rede de proteção a mulheres vítimas de violência doméstica é ampliada em Goiás",
    slug: "rede-protecao-mulheres-violencia-domestica-goias",
    summary: "Novos centros de atendimento serão inaugurados em 15 municípios do interior goiano.",
    content: `<p>O governo de Goiás inaugura 15 novos Centros de Referência de Atendimento à Mulher em municípios do interior, ampliando a rede de proteção para vítimas de violência doméstica e familiar.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['seguranca'],
    author: "Pedro Alves",
    publishedAt: "2025-02-21T10:00:00",
    updatedAt:  "2025-02-21T10:00:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },

  // ── MAIS NOTÍCIAS VARIADAS (15 notícias) ──────────────────────────
  {
    id: "86",
    title: "Pesquisa da UFG mapeia biodiversidade do cerrado goiano",
    slug: "pesquisa-ufg-biodiversidade-cerrado-goiano",
    summary: "Estudo identifica 340 espécies ameaçadas e propõe criação de novos corredores ecológicos.",
    content: `<p>Pesquisadores da UFG publicaram o maior levantamento já feito da biodiversidade do cerrado goiano, identificando 340 espécies ameaçadas e propondo a criação de corredores ecológicos entre unidades de conservação.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1518020382113-a7e8fc38eac9?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['politica'],
    author: "Ana Souza",
    publishedAt: "2025-02-20T10:00:00",
    updatedAt:  "2025-02-20T10:00:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },
  {
    id: "87",
    title: "Goiânia ganha premiação de cidade mais verde do Centro-Oeste",
    slug: "goiania-cidade-mais-verde-centro-oeste",
    summary: "Capital tem 22 m² de área verde por habitante, acima da média nacional e da recomendação da ONU.",
    content: `<p>Goiânia recebeu o prêmio de cidade mais verde do Centro-Oeste pelo segundo ano consecutivo, com 22 m² de área verde por habitante, superando a média nacional de 15 m² e a recomendação de 12 m² da ONU.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['politica'],
    author: "Carlos Lima",
    publishedAt: "2025-02-19T09:00:00",
    updatedAt:  "2025-02-19T09:00:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },
  {
    id: "88",
    title: "Startup de saúde goiana lança app para monitoramento de doenças crônicas",
    slug: "startup-saude-goiana-app-doencas-cronicas",
    summary: "Aplicativo já tem 80 mil usuários cadastrados e foi adotado por planos de saúde de seis estados.",
    content: `<p>A healthtech goiana VidaPlus lançou versão atualizada de seu aplicativo para monitoramento de diabetes, hipertensão e insuficiência cardíaca, com 80 mil usuários e parceria com 12 planos de saúde.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['economia'],
    author: "Pedro Alves",
    publishedAt: "2025-02-18T10:00:00",
    updatedAt:  "2025-02-18T10:00:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },
  {
    id: "89",
    title: "Festival de cinema de Goiânia anuncia programação com 120 filmes",
    slug: "festival-cinema-goiania-120-filmes",
    summary: "Mostra Cinematográfica de Goiânia chega à 18ª edição com produções de 40 países.",
    content: `<p>A 18ª Mostra Cinematográfica de Goiânia apresenta 120 filmes de 40 países, com seções competitivas de longa e curta-metragem e uma retrospectiva dedicada ao cinema goiano.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['entretenimento'],
    author: "Ana Souza",
    publishedAt: "2025-02-17T09:00:00",
    updatedAt:  "2025-02-17T09:00:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },
  {
    id: "90",
    title: "Delegação goiana conquista 15 medalhas nos Jogos Regionais do Centro-Oeste",
    slug: "delegacao-goiana-medalhas-jogos-regionais",
    summary: "Atletismo, natação e ginástica artística foram as modalidades de maior destaque do estado.",
    content: `<p>A delegação goiana conquistou 15 medalhas nos Jogos Regionais do Centro-Oeste — 6 ouros, 5 pratas e 4 bronzes — ficando em segundo lugar geral na classificação por estados.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['esporte'],
    author: "Pedro Alves",
    publishedAt: "2025-02-16T10:00:00",
    updatedAt:  "2025-02-16T10:00:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },
  {
    id: "91",
    title: "Governo lança programa de apoio a produtores de agricultura familiar",
    slug: "governo-programa-agricultura-familiar",
    summary: "Iniciativa oferece assistência técnica, crédito facilitado e acesso a mercados institucionais.",
    content: `<p>O programa Goiás Familiar vai beneficiar 45 mil produtores de agricultura familiar com assistência técnica gratuita, crédito a juros de 3% ao ano e acesso privilegiado ao PNAE e PAA.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['economia'],
    author: "Carlos Lima",
    publishedAt: "2025-02-15T09:00:00",
    updatedAt:  "2025-02-15T09:00:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },
  {
    id: "92",
    title: "Goiás recebe prêmio nacional de gestão fiscal responsável",
    slug: "goias-premio-gestao-fiscal-responsavel",
    summary: "Estado é reconhecido pela terceira vez consecutiva pela Secretaria do Tesouro Nacional.",
    content: `<p>Goiás recebeu pelo terceiro ano seguido o Prêmio de Gestão Fiscal Responsável da Secretaria do Tesouro Nacional, sendo um dos cinco estados com as finanças públicas mais equilibradas do Brasil.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['politica'],
    author: "Maria Santos",
    publishedAt: "2025-02-14T10:00:00",
    updatedAt:  "2025-02-14T10:00:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },
  {
    id: "93",
    title: "Novos talentos goianos dominam competição nacional de jovens empresários",
    slug: "talentos-goianos-competicao-jovens-empresarios",
    summary: "Três startups do estado foram finalistas no maior prêmio de empreendedorismo jovem do Brasil.",
    content: `<p>Três startups goianas chegaram à final do Prêmio Nacional de Jovens Empresários, sendo uma delas — a edtech GoiasTech — a vencedora na category tecnologia educacional com um app de alfabetização.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['economia'],
    author: "Ana Souza",
    publishedAt: "2025-02-13T09:00:00",
    updatedAt:  "2025-02-13T09:00:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },
  {
    id: "94",
    title: "Escola pública goiana vence olimpíada nacional de matemática",
    slug: "escola-publica-goiana-olimpiada-matematica",
    summary: "Estudante de 16 anos de Jataí representa o Brasil na competição internacional da área.",
    content: `<p>Maria Clara Oliveira, 16 anos, aluna da rede pública de Jataí, venceu a Olimpíada Nacional de Matemática na category ensino médio e representará o Brasil na competição internacional em julho.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1509062522246-3755977927d7?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['politica'],
    author: "Pedro Alves",
    publishedAt: "2025-02-12T10:00:00",
    updatedAt:  "2025-02-12T10:00:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },
  {
    id: "95",
    title: "Goiás atinge meta de reciclagem e se torna referência nacional em resíduos sólidos",
    slug: "goias-meta-reciclagem-referencia-nacional",
    summary: "Estado recicla 28% do lixo produzido, superando a média nacional de 4% e meta do Plano Nacional.",
    content: `<p>Goiás atingiu o índice de reciclagem de 28% dos resíduos sólidos produzidos no estado, tornando-se referência nacional e sendo convidado a apresentar seu modelo em conferência da ONU sobre clima.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['politica'],
    author: "Carlos Lima",
    publishedAt: "2025-02-11T09:00:00",
    updatedAt:  "2025-02-11T09:00:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },
  {
    id: "96",
    title: "Hospital das Clínicas de Goiânia realiza primeiro transplante de face do Centro-Oeste",
    slug: "hc-goiania-transplante-face-centro-oeste",
    summary: "Procedimento durou 22 horas e envolveu equipe de 40 profissionais de saúde.",
    content: `<p>O Hospital das Clínicas da UFG realizou o primeiro transplante de face do Centro-Oeste, com cirurgia de 22 horas envolvendo 40 profissionais. O paciente, de 34 anos, evoluiu bem no pós-operatório.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1551190822-a9333d879b1f?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['politica'],
    author: "Maria Santos",
    publishedAt: "2025-02-10T10:00:00",
    updatedAt:  "2025-02-10T10:00:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },
  {
    id: "97",
    title: "Goiás investe R$ 800 milhões na expansão da rede de creches municipais",
    slug: "goias-investe-expansao-creches-municipais",
    summary: "Programa prevê a construção de 180 novas creches até 2026, atendendo 45 mil crianças.",
    content: `<p>O programa Creche para Todos vai construir 180 novas unidades de educação infantil em Goiás até 2026, atendendo 45 mil crianças de zero a três anos que hoje estão na fila de espera.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1576495199011-eb94736d05d6?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['politica'],
    author: "Ana Souza",
    publishedAt: "2025-02-09T09:00:00",
    updatedAt:  "2025-02-09T09:00:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },
  {
    id: "98",
    title: "Tradicional Festa do Divino de Pirenópolis é reconhecida como Patrimônio Cultural",
    slug: "festa-divino-pirenopolis-patrimonio-cultural",
    summary: "Iphan reconhece manifestação cultural de mais de 200 anos como patrimônio imaterial do Brasil.",
    content: `<p>O Iphan reconheceu a Festa do Divino Espírito Santo de Pirenópolis como Patrimônio Cultural Imaterial do Brasil, celebrando mais de 200 anos de tradição que mistura religiosidade e manifestações folclóricas.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['entretenimento'],
    author: "Pedro Alves",
    publishedAt: "2025-02-08T10:00:00",
    updatedAt:  "2025-02-08T10:00:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },
  {
    id: "99",
    title: "Goiás se torna o maior produtor de sorgo do Brasil",
    slug: "goias-maior-produtor-sorgo-brasil",
    summary: "Cultura ganha espaço como alternativa ao milho e representa nova fronteira para o agronegócio estadual.",
    content: `<p>Goiás assumiu a liderança nacional na produção de sorgo, com 4,2 milhões de toneladas na safra 2024/25, superando Minas Gerais. A cultura se expande como alternativa ao milho nas regiões de segunda safra.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['economia'],
    author: "Carlos Lima",
    publishedAt: "2025-02-07T09:00:00",
    updatedAt:  "2025-02-07T09:00:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },
  {
    id: "100",
    title: "Goiânia é eleita uma das 10 melhores cidades para se viver no Brasil",
    slug: "goiania-melhores-cidades-para-viver-brasil",
    summary: "Ranking leva em conta qualidade de vida, infraestrutura, saúde, educação e oportunidades de trabalho.",
    content: `<p>Goiânia foi eleita a 7ª melhor cidade para se viver no Brasil em ranking que avalia qualidade de vida, infraestrutura urbana, saúde pública, educação e oportunidades de emprego nas 50 maiores cidades do país.</p>`,
    thumbnailUrl: "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=800&q=80",
    thumbnailCaption: "Teste caption 123",
    category: CATEGORY_MAP['politica'],
    author: "Ana Souza",
    publishedAt: "2025-02-06T10:00:00",
    updatedAt:  "2025-02-06T10:00:00",
    isPublished: true,
    isHighlight: false,
    isEditorial: true, 
    tags: []
  },
]


export const PESSOAS_MOCK: Person[] = [
  { id: "1", name: "Ana Souza", position: "Editora-chefe", biography: "15 anos de experiência em jornalismo político e investigativo. Ex-correspondente internacional pela América Latina.", photoUrl: "", email: "ana@diariogoiano.com.br" },
  { id: "2", name: "Carlos Lima", position: "Editor de Economia", biography: "Especializado em cobertura econômica e mercado financeiro. MBA em Finanças pela FGV e ex-repórter do Valor Econômico.", photoUrl: "", email: "carlos@diariogoiano.com.br" },
  { id: "3", name: "Maria Santos", position: "Jornalista", biography: "Cobre pautas sociais, direitos humanos e políticas públicas há 8 anos. Prêmio Vladimir Herzog de Anistia e Direitos Humanos 2022.", photoUrl: "", email: "maria@diariogoiano.com.br" },
  { id: "4", name: "Pedro Alves", position: "Repórter Multimídia", biography: "Fotojornalista e repórter. Especializado em cultura, meio ambiente e esporte. Fotógrafo oficial do Goiás Esporte Clube por 3 anos.", photoUrl: "", email: "pedro@diariogoiano.com.br" },
]
